#+TITLE: Theory of BlockChain 


* History of Block chain and structure of blocks

  in 2010 the first bitcoin purchase was registered which showed acceptance to crypto-currency. and in 2014 LHV-Pank started research into blockchain and they introduced a block chain based app called Cuber Wallet.
  in 2014, Ethereum Project - a block chain platform with the ability to build decenteralized applications - is funded by a crowd sale.
  by September 2015, major financial institutes started commiting to research block chain. and financial giants start investing in chain.com (they invested around $30m).
  
** So, what is blockchain?
   it is a distributed chain of blocks! or a distributed ledger. And a ledger is a log on income/outcome (money earned/ money spent) and most financial institutes would have a very detailed ledger in which they keep all the details of the customer's account spending and credit and debit.
   in a financial software, a bank keeps all the data in one place (one centeral server) and the user makes requests to view these ledgers, but block chain drives the idea of having that ledger being distributed and every user would have a copy of their ledger (a copy of the ledger is saved at their computers!)
   
** So, what is a block? 
   the structure of a single block in the block chain is composed of three elements:
*** Data:
    which is the data that is saved within that block, maybe the data is a finiancial data, a single transaction or even an account balance.
*** Hash of the block:
    is the sum of the data in this block! which can be some sort of a hash that is generated from the data of the block and the hash of the previous block to generate a unique signature for this block.
*** Hash of the previous block:
    same as the hash but just for the previous blcok to this one

** They say that block chain is scured, how?
   the security mechanism that block chain implements is 
*** destributing shreds of information over multiple blocks:
    which makes the work of a hacker much more difficult to tamper with the whole chain.
*** the hash of a block is a recursive mechanism of previous blocks hashes
    which means if one block hash changes, then the subsequent blocks will not be have hashes that correspond with the previous block's hash making it invalid and very easy to spot where the breach happened and which data it happened to.
*** concept of work:
    for a block to change and for that change to be valid a hacker or editor must provide a "proof of work" which is a very complex mathematical operation that their computers have to excute in order to validate the change which makes tampering with the data exponentially difficult.
*** consensus algorithms:
    say that the hacker managed to calculate the proof of work for all subsequent blocks using a quantum computer. The hacker will have to still get the approval of all the people that have a copy of the block chain with them in order to change that single block and this is called consensus algorithm.
  
  for someone to tamper with data they will have to go through all of these security measures first which makes block chain the star of security.
